/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloc.notes;

import java.io.IOException;

import javax.swing.JOptionPane;

/**
 *
 * @author Remi
 */
public class GUI extends javax.swing.JFrame {
    private String file_name;
    private String file_text;
    private boolean not_saved;
    private boolean file_chooser_opened;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.file_chooser_opened = false;
    }
    
    public boolean get_file_chooser_opened(){
        return file_chooser_opened;
    }
    
    public void set_file_chooser_opened(boolean opened){
        this.file_chooser_opened = opened;
    } 
    
    public String get_file_name(){
        return this.file_name;
    }

    public void set_text(String text){
        this.file_text = text;
        this.text.setText(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        file_chooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fichier_menu = new javax.swing.JMenu();
        nouveau = new javax.swing.JMenuItem();
        nouvelle_fenetre = new javax.swing.JMenuItem();
        ouvrir = new javax.swing.JMenuItem();
        enregistrer = new javax.swing.JMenuItem();
        enregistrer_sous = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mise_en_page = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        quitter = new javax.swing.JMenuItem();
        edition_menu = new javax.swing.JMenu();
        annuler = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        couper = new javax.swing.JMenuItem();
        copier = new javax.swing.JMenuItem();
        coller = new javax.swing.JMenuItem();
        suppr = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        rechercher = new javax.swing.JMenuItem();
        rechercher_suivant = new javax.swing.JMenuItem();
        rechercher_precedent = new javax.swing.JMenuItem();
        remplacer = new javax.swing.JMenuItem();
        atteindre = new javax.swing.JMenuItem();
        selectionner_tout = new javax.swing.JMenuItem();
        date_heure = new javax.swing.JMenuItem();
        format_menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        affichage_menu = new javax.swing.JMenu();
        zoom_menu = new javax.swing.JMenu();
        zoom_avant = new javax.swing.JMenuItem();
        zoom_arriere = new javax.swing.JMenuItem();
        zoom_defaut = new javax.swing.JMenuItem();
        barre_etat_check = new javax.swing.JCheckBoxMenuItem();

        file_chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    file_chooserActionPerformed(evt);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(file_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(file_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bloc-notes");
        setPreferredSize(new java.awt.Dimension(800, 600));

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        fichier_menu.setText("Fichier");

        nouveau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        nouveau.setText("Nouveau");
        nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauActionPerformed(evt);
            }
        });
        fichier_menu.add(nouveau);

        nouvelle_fenetre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        nouvelle_fenetre.setText("Nouvelle fenêtre");
        nouvelle_fenetre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouvelle_fenetreActionPerformed(evt);
            }
        });
        fichier_menu.add(nouvelle_fenetre);

        ouvrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ouvrir.setText("Ouvrir...");
        ouvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvrirActionPerformed(evt);
            }
        });
        fichier_menu.add(ouvrir);

        enregistrer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        enregistrer.setText("Enregistrer");
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });
        fichier_menu.add(enregistrer);

        enregistrer_sous.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        enregistrer_sous.setText("Enregistrer sous...");
        enregistrer_sous.setToolTipText("");
        fichier_menu.add(enregistrer_sous);
        fichier_menu.add(jSeparator1);

        mise_en_page.setText("Mise en page");
        fichier_menu.add(mise_en_page);
        fichier_menu.add(jSeparator2);

        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        fichier_menu.add(quitter);

        jMenuBar1.add(fichier_menu);

        edition_menu.setText("Edition");

        annuler.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        edition_menu.add(annuler);
        edition_menu.add(jSeparator3);

        couper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        couper.setText("Couper");
        edition_menu.add(couper);

        copier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        copier.setText("Copier");
        edition_menu.add(copier);

        coller.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        coller.setText("Coller");
        edition_menu.add(coller);

        suppr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        suppr.setText("Supprimer");
        edition_menu.add(suppr);
        edition_menu.add(jSeparator4);

        rechercher.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        rechercher.setText("Rechercher");
        edition_menu.add(rechercher);

        rechercher_suivant.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        rechercher_suivant.setText("Rechercher le suivant");
        edition_menu.add(rechercher_suivant);

        rechercher_precedent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        rechercher_precedent.setText("Rechercher le précédent");
        edition_menu.add(rechercher_precedent);

        remplacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        remplacer.setText("Remplacer");
        edition_menu.add(remplacer);

        atteindre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        atteindre.setText("Atteindre");
        edition_menu.add(atteindre);

        selectionner_tout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        selectionner_tout.setText("Sélectionner tout");
        edition_menu.add(selectionner_tout);

        date_heure.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        date_heure.setText("Heure/Date");
        edition_menu.add(date_heure);

        jMenuBar1.add(edition_menu);

        format_menu.setText("Format");

        jMenuItem1.setText("Retour automatique à la ligne");
        format_menu.add(jMenuItem1);

        jMenuBar1.add(format_menu);

        affichage_menu.setText("Affichage");

        zoom_menu.setText("Zoom");

        zoom_avant.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ADD, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        zoom_avant.setText("Zoom avant");
        zoom_menu.add(zoom_avant);

        zoom_arriere.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SUBTRACT, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        zoom_arriere.setText("Zoom arrière");
        zoom_menu.add(zoom_arriere);

        zoom_defaut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        zoom_defaut.setText("Restaurer le zoom par défaut");
        zoom_menu.add(zoom_defaut);

        affichage_menu.add(zoom_menu);

        barre_etat_check.setSelected(true);
        barre_etat_check.setText("Barre d'état");
        affichage_menu.add(barre_etat_check);

        jMenuBar1.add(affichage_menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauActionPerformed
        //if not saved, ask to save
        if(this.file_text != this.text.getText() && !this.text.getText().equals("")){
            int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous enregistrer votre fichier avant de créer un nouveau fichier ?", "Enregistrer", JOptionPane.YES_NO_CANCEL_OPTION);
            if(reponse == JOptionPane.YES_OPTION){
                this.enregistrer.doClick();
            }else if(reponse == JOptionPane.NO_OPTION){
                //vider text
                this.text.setText("");
            }
            else{
                //cancel
                return;
            }
        }
        //vider text
        this.text.setText("");
    }//GEN-LAST:event_nouveauActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerActionPerformed

    private void ouvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvrirActionPerformed
        // TODO add your handling code here:
        jFrame1.pack();
        jFrame1.setVisible(true);
    }//GEN-LAST:event_ouvrirActionPerformed

    private void file_chooserActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_file_chooserActionPerformed
        //check if button cancel is clicked or open button is clicked
        this.file_name = file_chooser.getSelectedFile().getAbsolutePath();
        this.file_chooser_opened = true;
        if(file_chooser.getSelectedFile() == null){
            jFrame1.dispose();
            return;
        }
        BlocNotes.openFile();
        jFrame1.dispose();
        
    }//GEN-LAST:event_file_chooserActionPerformed

    private void nouvelle_fenetreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouvelle_fenetreActionPerformed
        //init a new BlocNotes window
        GUI new_gui = new GUI();
        new_gui.setVisible(true);
    }//GEN-LAST:event_nouvelle_fenetreActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enregistrerActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        //close the jFrame
        this.dispose();
        
    }//GEN-LAST:event_quitterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu affichage_menu;
    private javax.swing.JMenuItem annuler;
    private javax.swing.JMenuItem atteindre;
    private javax.swing.JCheckBoxMenuItem barre_etat_check;
    private javax.swing.JMenuItem coller;
    private javax.swing.JMenuItem copier;
    private javax.swing.JMenuItem couper;
    private javax.swing.JMenuItem date_heure;
    private javax.swing.JMenu edition_menu;
    private javax.swing.JMenuItem enregistrer;
    private javax.swing.JMenuItem enregistrer_sous;
    private javax.swing.JMenu fichier_menu;
    private javax.swing.JFileChooser file_chooser;
    private javax.swing.JMenu format_menu;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem mise_en_page;
    private javax.swing.JMenuItem nouveau;
    private javax.swing.JMenuItem nouvelle_fenetre;
    private javax.swing.JMenuItem ouvrir;
    private javax.swing.JMenuItem quitter;
    private javax.swing.JMenuItem rechercher;
    private javax.swing.JMenuItem rechercher_precedent;
    private javax.swing.JMenuItem rechercher_suivant;
    private javax.swing.JMenuItem remplacer;
    private javax.swing.JMenuItem selectionner_tout;
    private javax.swing.JMenuItem suppr;
    private javax.swing.JTextArea text;
    private javax.swing.JMenuItem zoom_arriere;
    private javax.swing.JMenuItem zoom_avant;
    private javax.swing.JMenuItem zoom_defaut;
    private javax.swing.JMenu zoom_menu;
    // End of variables declaration//GEN-END:variables
}
